#!/usr/bin/env python3

"""
Plot energy convergence data from gradient descent solvers.

This script can plot energy histories from CSV files generated by the gradient descent solvers.
It supports plotting single files or comparing multiple runs.
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import argparse
import glob
import os
from pathlib import Path


def plot_energy_convergence(csv_files, output_dir="plots", log_scale=True, save_plots=True, show_plots=False, error_lower_bound=1e-11):
    """
    Plot energy convergence from one or more CSV files.
    
    Parameters:
    -----------
    csv_files : list of str
        List of CSV file paths to plot
    output_dir : str
        Directory to save plots
    log_scale : bool
        Whether to use log scale for y-axis
    save_plots : bool
        Whether to save plots to files
    show_plots : bool
        Whether to display plots interactively
    error_lower_bound : float
        Lower bound for energy error plot to avoid log(0) issues
    """
    
    if save_plots:
        os.makedirs(output_dir, exist_ok=True)
    
    # Set up matplotlib for better plots
    plt.style.use('seaborn-v0_8' if 'seaborn-v0_8' in plt.style.available else 'default')
    
    # Sort files for consistent ordering (periodic cycles first, then chebyshev, then linesearch)
    def sort_key(filename):
        if 'linesearch' in filename:
            return (2, filename)  # linesearch comes after periodic and chebyshev
        elif 'chebyshev' in filename:
            # Extract chebyshev rate for proper ordering
            parts = Path(filename).stem.split('_')
            for part in parts:
                try:
                    rate = float(part)
                    if 0 <= rate <= 1:  # Valid chebyshev rate
                        return (1, rate)  # chebyshev rates ordered numerically
                except ValueError:
                    continue
            return (1, 0)  # fallback for chebyshev files
        elif 'periodic' in filename:
            # Extract cycle number for proper ordering
            parts = Path(filename).stem.split('_')
            for part in parts:
                if part.isdigit():
                    return (0, int(part))  # periodic cycles ordered numerically
            return (0, 0)
        return (3, filename)  # other files at the end
    
    csv_files = sorted(csv_files, key=sort_key)
    
    # First pass: read all data and find theoretical minimum energy
    all_data = []
    min_energy_achieved = float('inf')
    
    for csv_file in csv_files:
        try:
            data = pd.read_csv(csv_file)
            all_data.append((csv_file, data))
            # Find minimum energy in this run
            run_min = data['energy'].min()
            if run_min < min_energy_achieved:
                min_energy_achieved = run_min
        except Exception as e:
            print(f"Warning: Could not process {csv_file}: {e}")
            continue
    
    print(f"Theoretical minimum energy (estimated): {min_energy_achieved:.12e}")
    
    # Colors for different runs
    colors = plt.cm.tab10(np.linspace(0, 1, len(all_data)))
    
    # Create subplots
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    fig.suptitle('Gradient Descent Convergence Analysis', fontsize=16)
    
    for i, (csv_file, data) in enumerate(all_data):
        # Extract run name from filename and clean it up
        filename = Path(csv_file).stem
        if 'linesearch' in filename:
            run_name = 'Line Search'
            linestyle = '--'  # Dotted line for linesearch
            linewidth = 2.5
        elif 'chebyshev' in filename:
            # For chebyshev, extract tau rate
            parts = filename.replace('energies_', '').replace('gradient_chebyshev_', '').split('_')
            tau_rate = None
            for part in parts:
                try:
                    rate = float(part)
                    if 0 <= rate <= 1:  # Valid chebyshev rate
                        tau_rate = part
                        break
                except ValueError:
                    continue
            run_name = f'Chebyshev τ={tau_rate}' if tau_rate else 'Chebyshev'
            linestyle = '-.'  # Dash-dot line for chebyshev
            linewidth = 2.5
        else:
            # For periodic, extract cycle number
            parts = filename.replace('energies_', '').replace('gradient_periodic_', '').split('_')
            cycle_num = None
            for part in parts:
                if part.isdigit():
                    cycle_num = part
                    break
            run_name = f'Cycle {cycle_num}' if cycle_num else 'Periodic'
            linestyle = '-'  # Solid line for periodic
            linewidth = 2
        
        color = colors[i]
        
        # Compute energy error (difference from theoretical minimum)
        energy_error = data['energy'] - min_energy_achieved
        # Add configurable epsilon to avoid log(0) issues
        energy_error = np.maximum(energy_error, error_lower_bound)
        
        # Plot 1: Energy Error vs Iteration (log scale)
        axes[0, 0].semilogy(data['iteration'], energy_error, 
                       label=run_name, color=color, linewidth=linewidth, 
                       alpha=0.8, linestyle=linestyle)
        
        # Plot 2: Constraint Violation vs Iteration
        axes[0, 1].plot(data['iteration'], data['violation'], 
                       label=run_name, color=color, linewidth=linewidth, 
                       alpha=0.8, linestyle=linestyle)
        
        # Plot 3: Step Size (tau) vs Iteration
        if 'tau' in data.columns:
            axes[1, 0].plot(data['iteration'], data['tau'], 
                           label=run_name, color=color, linewidth=linewidth, 
                           alpha=0.8, linestyle=linestyle)
        
        # Plot 4: Gradient Norm vs Iteration
        if 'gradient_norm' in data.columns:
            axes[1, 1].plot(data['iteration'], data['gradient_norm'], 
                           label=run_name, color=color, linewidth=linewidth, 
                           alpha=0.8, linestyle=linestyle)
    
    # Configure subplots
    axes[0, 0].set_xlabel('Iteration')
    axes[0, 0].set_ylabel('Energy Error: E(u) - E*')
    axes[0, 0].set_title('Energy Error Convergence (Log Scale)')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend()
    axes[0, 0].set_ylim(bottom=error_lower_bound)  # Set configurable lower bound
    
    axes[0, 1].set_xlabel('Iteration')
    axes[0, 1].set_ylabel('Constraint Violation')
    axes[0, 1].set_title('Constraint Violation')
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].legend()
    if log_scale:
        axes[0, 1].set_yscale('log')
    
    axes[1, 0].set_xlabel('Iteration')
    axes[1, 0].set_ylabel('Step Size τ')
    axes[1, 0].set_title('Step Size Evolution')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend()
    if log_scale:
        axes[1, 0].set_yscale('log')
    
    axes[1, 1].set_xlabel('Iteration')
    axes[1, 1].set_ylabel('Gradient Norm |∇g|²')
    axes[1, 1].set_title('Gradient Norm Evolution')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend()
    if log_scale:
        axes[1, 1].set_yscale('log')
    
    plt.tight_layout()
    
    if save_plots:
        # Generate output filename
        if len(csv_files) == 1:
            base_name = Path(csv_files[0]).stem
        else:
            base_name = f"comparison_{len(csv_files)}_runs"
        
        output_file = os.path.join(output_dir, f"{base_name}_convergence.png")
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Plot saved to: {output_file}")
    
    if show_plots:
        plt.show()
    else:
        plt.close()


def plot_energy_comparison(csv_files, output_dir="plots", save_plots=True, show_plots=False, error_lower_bound=1e-11):
    """
    Create a focused comparison plot of energy error convergence.
    
    Parameters:
    -----------
    csv_files : list of str
        List of CSV file paths to plot
    output_dir : str
        Directory to save plots
    save_plots : bool
        Whether to save plots to files
    show_plots : bool
        Whether to display plots interactively
    error_lower_bound : float
        Lower bound for energy error to avoid log(0) issues
    """
    
    if save_plots:
        os.makedirs(output_dir, exist_ok=True)
    
    plt.figure(figsize=(12, 8))
    
    # Sort files for consistent ordering
    def sort_key(filename):
        if 'linesearch' in filename:
            return (2, filename)  # linesearch comes after periodic and chebyshev
        elif 'chebyshev' in filename:
            # Extract chebyshev rate for proper ordering
            parts = Path(filename).stem.split('_')
            for part in parts:
                try:
                    rate = float(part)
                    if 0 <= rate <= 1:  # Valid chebyshev rate
                        return (1, rate)  # chebyshev rates ordered numerically
                except ValueError:
                    continue
            return (1, 0)  # fallback for chebyshev files
        elif 'periodic' in filename:
            # Extract cycle number for proper ordering
            parts = Path(filename).stem.split('_')
            for part in parts:
                if part.isdigit():
                    return (0, int(part))  # periodic cycles ordered numerically
            return (0, 0)
        return (3, filename)  # other files at the end
    
    csv_files = sorted(csv_files, key=sort_key)
    
    # First pass: find theoretical minimum energy
    min_energy_achieved = float('inf')
    all_data = []
    
    for csv_file in csv_files:
        try:
            data = pd.read_csv(csv_file)
            all_data.append((csv_file, data))
            run_min = data['energy'].min()
            if run_min < min_energy_achieved:
                min_energy_achieved = run_min
        except Exception as e:
            print(f"Warning: Could not process {csv_file}: {e}")
            continue
    
    print(f"Theoretical minimum energy for comparison plot: {min_energy_achieved:.12e}")
    
    colors = plt.cm.tab10(np.linspace(0, 1, len(all_data)))
    
    for i, (csv_file, data) in enumerate(all_data):
        # Extract run name and styling
        filename = Path(csv_file).stem
        if 'linesearch' in filename:
            run_name = 'Line Search'
            linestyle = '--'
            linewidth = 3
        elif 'chebyshev' in filename:
            # For chebyshev, extract tau rate
            parts = filename.replace('energies_', '').replace('gradient_chebyshev_', '').split('_')
            tau_rate = None
            for part in parts:
                try:
                    rate = float(part)
                    if 0 <= rate <= 1:  # Valid chebyshev rate
                        tau_rate = part
                        break
                except ValueError:
                    continue
            run_name = f'Chebyshev τ={tau_rate}' if tau_rate else 'Chebyshev'
            linestyle = '-.'  # Dash-dot line for chebyshev
            linewidth = 3
        else:
            # For periodic, extract cycle number
            parts = filename.replace('energies_', '').replace('gradient_periodic_', '').split('_')
            cycle_num = None
            for part in parts:
                if part.isdigit():
                    cycle_num = part
                    break
            run_name = f'Cycle {cycle_num}' if cycle_num else 'Periodic'
            linestyle = '-'
            linewidth = 2.5
        
        # Compute energy error
        energy_error = data['energy'] - min_energy_achieved
        energy_error = np.maximum(energy_error, error_lower_bound)  # Use configurable lower bound
        
        plt.semilogy(data['iteration'], energy_error, 
                label=run_name, color=colors[i], linewidth=linewidth, 
                alpha=0.8, linestyle=linestyle)
    
    plt.xlabel('Iteration', fontsize=14)
    plt.ylabel('Energy Error: E(u) - E*', fontsize=14)
    plt.title('Energy Error Convergence Comparison (Log Scale)', fontsize=16)
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=12)
    plt.ylim(bottom=error_lower_bound)  # Set configurable lower bound
    plt.tight_layout()
    
    if save_plots:
        output_file = os.path.join(output_dir, "energy_error_comparison.png")
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Energy error comparison plot saved to: {output_file}")
    
    if show_plots:
        plt.show()
    else:
        plt.close()


def main():
    parser = argparse.ArgumentParser(description="Plot energy convergence from gradient descent CSV files")
    parser.add_argument("files", nargs="*", help="CSV files to plot. If none specified, searches for energies_*.csv in output/")
    parser.add_argument("--output-dir", default="plots", help="Directory to save plots")
    parser.add_argument("--linear-scale", action="store_true", help="Use linear scale instead of log scale")
    parser.add_argument("--no-save", action="store_true", help="Don't save plots to files")
    parser.add_argument("--show", action="store_true", help="Display plots interactively")
    parser.add_argument("--pattern", default="output/energies_*.csv", help="Glob pattern to find CSV files if none specified")
    parser.add_argument("--error-lower-bound", type=float, default=1e-11, help="Lower bound for energy error plot (default: 1e-11)")
    
    args = parser.parse_args()
    
    # Find CSV files
    if args.files:
        csv_files = args.files
    else:
        csv_files = glob.glob(args.pattern)
        if not csv_files:
            print(f"No CSV files found matching pattern: {args.pattern}")
            print("Run gradient descent with --energy-log option first, or specify files explicitly.")
            return
    
    # Validate files exist
    csv_files = [f for f in csv_files if os.path.exists(f)]
    if not csv_files:
        print("No valid CSV files found.")
        return
    
    print(f"Found {len(csv_files)} CSV files:")
    for f in csv_files:
        print(f"  - {f}")
    
    # Create plots
    plot_energy_convergence(
        csv_files,
        output_dir=args.output_dir,
        log_scale=not args.linear_scale,
        save_plots=not args.no_save,
        show_plots=args.show,
        error_lower_bound=args.error_lower_bound
    )
    
    # Create energy comparison plot if multiple files
    if len(csv_files) > 1:
        plot_energy_comparison(
            csv_files,
            output_dir=args.output_dir,
            save_plots=not args.no_save,
            show_plots=args.show,
            error_lower_bound=args.error_lower_bound
        )


if __name__ == "__main__":
    main()